/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__models
#define __PYX_HAVE__models

struct c_DcBrushedMotor;

/* "models.pyx":5
 * 
 * 
 * cdef public class DcBrushedMotor[object c_DcBrushedMotor, type c_DcBrushedMotor_t]:             # <<<<<<<<<<<<<<
 *     def __init__(self, nominal_voltage, stall_torque, stall_current, free_current, free_speed):
 *         """Holds the constants for a DC brushed motor.
 */
struct c_DcBrushedMotor {
  PyObject_HEAD
};

#ifndef __PYX_HAVE_API__models

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) c_DcBrushedMotor_t;

__PYX_EXTERN_C PyObject *gearbox(PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *elevator(PyObject *, PyObject *, PyObject *, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *flywheel(PyObject *, PyObject *, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *drivetrain(PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *single_jointed_arm(PyObject *, PyObject *, PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__models */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmodels(void);
#else
PyMODINIT_FUNC PyInit_models(void);
#endif

#endif /* !__PYX_HAVE__models */
