/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__profiles
#define __PYX_HAVE__profiles


#ifndef __PYX_HAVE_API__profiles

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *generate_trapezoid_profile(PyObject *, PyObject *, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *generate_s_curve_profile(PyObject *, PyObject *, PyObject *, PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__profiles */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initprofiles(void);
#else
PyMODINIT_FUNC PyInit_profiles(void);
#endif

#endif /* !__PYX_HAVE__profiles */
