/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__system
#define __PYX_HAVE__system

struct c_System;

/* "system.pyx":16
 * 
 * 
 * cdef public class System[object c_System, type c_System_t]:             # <<<<<<<<<<<<<<
 *     __metaclass__ = abc.ABCMeta
 * 
 */
struct c_System {
  PyObject_HEAD
  struct __pyx_vtabstruct_6system_System *__pyx_vtab;
};

#ifndef __PYX_HAVE_API__system

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) c_System_t;

#endif /* !__PYX_HAVE_API__system */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsystem(void);
#else
PyMODINIT_FUNC PyInit_system(void);
#endif

#endif /* !__PYX_HAVE__system */
